CREATE TABLE IF NOT EXISTS "umastudy_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "umastudy_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "umastudy_buildings" (
	"id" varchar(5) PRIMARY KEY NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "umastudy_event_rooms" (
	"event_id" integer NOT NULL,
	"building" varchar(8) NOT NULL,
	"room_id" varchar(16) NOT NULL,
	CONSTRAINT "umastudy_event_rooms_event_id_room_id_pk" PRIMARY KEY("event_id","room_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "umastudy_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "umastudy_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"live_event_id" integer NOT NULL,
	"name" text NOT NULL,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	CONSTRAINT "live_event_id_starts_unique" UNIQUE("live_event_id","starts_at")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "umastudy_rooms" (
	"id" varchar(16) NOT NULL,
	"building" varchar(8) NOT NULL,
	CONSTRAINT "umastudy_rooms_building_id_pk" PRIMARY KEY("building","id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "umastudy_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "umastudy_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "umastudy_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "umastudy_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "umastudy_account" ADD CONSTRAINT "umastudy_account_user_id_umastudy_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."umastudy_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "umastudy_event_rooms" ADD CONSTRAINT "umastudy_event_rooms_event_id_umastudy_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."umastudy_events"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "umastudy_event_rooms" ADD CONSTRAINT "umastudy_event_rooms_building_room_id_umastudy_rooms_building_id_fk" FOREIGN KEY ("building","room_id") REFERENCES "public"."umastudy_rooms"("building","id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "umastudy_rooms" ADD CONSTRAINT "umastudy_rooms_building_umastudy_buildings_id_fk" FOREIGN KEY ("building") REFERENCES "public"."umastudy_buildings"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "umastudy_session" ADD CONSTRAINT "umastudy_session_user_id_umastudy_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."umastudy_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "umastudy_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_id_idx" ON "umastudy_event_rooms" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "room_id_idx" ON "umastudy_event_rooms" USING btree ("room_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "live_event_id" ON "umastudy_events" USING btree ("live_event_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "starts_at_idx" ON "umastudy_events" USING btree ("starts_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ends_at_idx" ON "umastudy_events" USING btree ("ends_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "umastudy_session" USING btree ("user_id");