export const LIVE_API_URL =
  "https://25live.collegenet.com/25live/data/umass/run";

export const BLDG_CODES = [
  "ILC",
  "ARND",
  "BART",
  "BOYD",
  "FURC",
  "HILS",
  "MOR1",
  "MOR2",
  "MOR3",
  "MOR4",
  "MOR",
  "SOM",
  "THOM",
  "HAS",
  "AEBC",
  "JAME",
  "BCA",
  "BOWD",
  "BFLD",
  "CHEN",
  "CMPS",
  "CNTE",
  "DB",
  "CROT",
  "DKSN",
  "ECSC",
  "ELAB",
  "ELABII",
  "ELM",
  "EMLY",
  "FAC",
  "FREN",
  "FERN",
  "GDLL",
  "GORD",
  "GORM",
  "GSMN",
  "GUN",
  "HERT",
  "HICK",
  "HOLD",
  "LGRC",
  "LGRT",
  "LIB",
  "LSL",
  "MACH",
  "MARC",
  "MARX",
  "MRST",
  "NAH",
  "SAB",
  "SC",
  "SKIN",
  "STK",
  "TOBN",
  "CHN",
  "MAH",
  "ISB",
  "GOES",
  "FLIN",
] as const;

export const BLDG_NAMES: Record<(typeof BLDG_CODES)[number], string> = {
  ILC: "Integrative Learning Center",
  ARND: "Arnold House",
  BART: "Bartlett Hall",
  BOYD: "Boyden Gym",
  FURC: "Furculo Hall",
  HILS: "Hills House",
  MOR1: "Morrill Science Center (Bldg I)",
  MOR2: "Morrill Science Center (Bldg II)",
  MOR3: "Morrill Science Center (Bldg III)",
  MOR4: "Morrill Science Center (Bldg IV)",
  MOR: "Morrill Science Center",
  SOM: "School of Management",
  THOM: "Thompson Hall",
  HAS: "Hasbrouck Lab",
  AEBC: "Ag. Engin. Farm Srvc Bldg",
  JAME: "James House",
  BCA: "Bromery Center for Arts",
  BOWD: "Bowditch Hall",
  BFLD: "Butterfield House",
  CHEN: "Chenoweth Lab",
  CMPS: "Computer Science Building",
  CNTE: "Conte Polymer Resource Center",
  DB: "John Olver Design Building",
  CROT: "Crotty Hall",
  DKSN: "Dickinson",
  ECSC: "Engineering & Computer Science II",
  ELAB: "Engineering Laboratory",
  ELABII: "Engineering Lab II",
  ELM: "Elm",
  EMLY: "Emily Dickinson House",
  FAC: "Fine Arts Center",
  FREN: "French Hall",
  FERN: "Fernald Hall",
  GDLL: "Goodell Building",
  GORD: "Gordon Hall",
  GORM: "Gorman House",
  GSMN: "Goessmann Lab",
  GUN: "Gunness Laboratory",
  HERT: "Herter Hall",
  HICK: "Curry Hicks",
  HOLD: "Holdsworth Hall",
  LGRC: "Lederle Graduate Research Center",
  LGRT: "Lederle Graduate Research Tower",
  LIB: "W.E.B. Dubois Library",
  LSL: "Life Sciences Laboratory",
  MACH: "Machmer Hall",
  MARC: "Marcus Hall",
  MARX: "Marshall Hall",
  MRST: "Marston Hall",
  NAH: "New Africa House",
  SAB: "Studio Arts",
  SC: "South College",
  SKIN: "Skinner Hall",
  STK: "Stockbridge Hall",
  TOBN: "Tobin Hall",
  CHN: "Chenoweth Lab",
  MAH: "Mahar",
  ISB: "Integrated Sciences Building",
  GOES: "Goessmann Laboratory",
  FLIN: "Flint Laboratory",
};
